version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    ports:
      - "8000:8000"  # FastAPI Port
      - "5173:5173"  # SvelteKit Port
